# 1 - Numpy


<br>
<br>

<img src="https://raw.githubusercontent.com/Hack-io-AI/ai_images/main/numpy.png" style="width:400px;"/>

<h1>Tabla de Contenidos<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1---¿Qué-es-Numpy?" data-toc-modified-id="1---¿Qué-es-Numpy?-1">1 - ¿Qué es Numpy?</a></span></li><li><span><a href="#2---Recordatorio-de-álgebra" data-toc-modified-id="2---Recordatorio-de-álgebra-2">2 - Recordatorio de álgebra</a></span><ul class="toc-item"><li><span><a href="#2.1---Concepto-de-tensor" data-toc-modified-id="2.1---Concepto-de-tensor-2.1">2.1 - Concepto de tensor</a></span></li><li><span><a href="#2.2---Operaciones-con-vectores" data-toc-modified-id="2.2---Operaciones-con-vectores-2.2">2.2 - Operaciones con vectores</a></span><ul class="toc-item"><li><span><a href="#2.2.1---Espacio-vectorial" data-toc-modified-id="2.2.1---Espacio-vectorial-2.2.1">2.2.1 - Espacio vectorial</a></span></li><li><span><a href="#2.2.2---Base-vectorial" data-toc-modified-id="2.2.2---Base-vectorial-2.2.2">2.2.2 - Base vectorial</a></span></li><li><span><a href="#2.2.3---Suma-de-vectores" data-toc-modified-id="2.2.3---Suma-de-vectores-2.2.3">2.2.3 - Suma de vectores</a></span></li><li><span><a href="#2.2.4---Producto-escalar" data-toc-modified-id="2.2.4---Producto-escalar-2.2.4">2.2.4 - Producto escalar</a></span></li><li><span><a href="#2.2.5---Producto-vectorial" data-toc-modified-id="2.2.5---Producto-vectorial-2.2.5">2.2.5 - Producto vectorial</a></span></li></ul></li><li><span><a href="#2.3---Operaciones-con-matrices" data-toc-modified-id="2.3---Operaciones-con-matrices-2.3">2.3 - Operaciones con matrices</a></span><ul class="toc-item"><li><span><a href="#2.3.1---Suma-de-matrices" data-toc-modified-id="2.3.1---Suma-de-matrices-2.3.1">2.3.1 - Suma de matrices</a></span></li><li><span><a href="#2.3.2---Producto-matricial" data-toc-modified-id="2.3.2---Producto-matricial-2.3.2">2.3.2 - Producto matricial</a></span></li><li><span><a href="#2.3.3---Matriz-Identidad" data-toc-modified-id="2.3.3---Matriz-Identidad-2.3.3">2.3.3 - Matriz Identidad</a></span></li><li><span><a href="#2.3.4---Matriz-traspuesta--(hermítica)" data-toc-modified-id="2.3.4---Matriz-traspuesta--(hermítica)-2.3.4">2.3.4 - Matriz traspuesta  (hermítica)</a></span></li><li><span><a href="#2.3.5---Matriz-Inversa" data-toc-modified-id="2.3.5---Matriz-Inversa-2.3.5">2.3.5 - Matriz Inversa</a></span></li><li><span><a href="#2.3.6---Determinante" data-toc-modified-id="2.3.6---Determinante-2.3.6">2.3.6 - Determinante</a></span></li></ul></li></ul></li><li><span><a href="#3---Operaciones-con-NumPy" data-toc-modified-id="3---Operaciones-con-NumPy-3">3 - Operaciones con NumPy</a></span><ul class="toc-item"><li><span><a href="#3.1---Creación-de-arrays" data-toc-modified-id="3.1---Creación-de-arrays-3.1">3.1 - Creación de arrays</a></span></li><li><span><a href="#3.2---Dimensiones-y-acceso-a-elementos" data-toc-modified-id="3.2---Dimensiones-y-acceso-a-elementos-3.2">3.2 - Dimensiones y acceso a elementos</a></span></li><li><span><a href="#3.3---Suma-de-vectores" data-toc-modified-id="3.3---Suma-de-vectores-3.3">3.3 - Suma de vectores</a></span></li><li><span><a href="#3.4---Producto-por-escalares" data-toc-modified-id="3.4---Producto-por-escalares-3.4">3.4 - Producto por escalares</a></span></li><li><span><a href="#3.5---Producto-escalar-de-vectores" data-toc-modified-id="3.5---Producto-escalar-de-vectores-3.5">3.5 - Producto escalar de vectores</a></span></li><li><span><a href="#3.6---Producto-vectorial" data-toc-modified-id="3.6---Producto-vectorial-3.6">3.6 - Producto vectorial</a></span></li><li><span><a href="#3.7---Suma-de-matrices" data-toc-modified-id="3.7---Suma-de-matrices-3.7">3.7 - Suma de matrices</a></span></li><li><span><a href="#3.8---Producto-escalar-de-matrices" data-toc-modified-id="3.8---Producto-escalar-de-matrices-3.8">3.8 - Producto escalar de matrices</a></span></li><li><span><a href="#3.9---Producto-matricial" data-toc-modified-id="3.9---Producto-matricial-3.9">3.9 - Producto matricial</a></span></li><li><span><a href="#3.10---Matriz-identidad" data-toc-modified-id="3.10---Matriz-identidad-3.10">3.10 - Matriz identidad</a></span></li><li><span><a href="#3.11---Matriz-traspuesta" data-toc-modified-id="3.11---Matriz-traspuesta-3.11">3.11 - Matriz traspuesta</a></span></li><li><span><a href="#3.12---Matriz-inversa" data-toc-modified-id="3.12---Matriz-inversa-3.12">3.12 - Matriz inversa</a></span></li><li><span><a href="#3.13---Determinante" data-toc-modified-id="3.13---Determinante-3.13">3.13 - Determinante</a></span></li><li><span><a href="#3.14---Otra-operaciones" data-toc-modified-id="3.14---Otra-operaciones-3.14">3.14 - Otra operaciones</a></span></li></ul></li></ul></div>

## 1 - ¿Qué es Numpy?

NumPy (Numerical Python) es el paquete fundamental para computación cientifíca en python. Es una librería de python nos permite manejar vectores, matrices, [tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) (arrays multidimensionales) y además realizar todas las operaciones matemáticas y lógicas de los mismos, como la manipulación de la dimensión, ordenado, selección, I/O, operaciones estadísticas, transformadas de Fourier, simulación aleatoria y un largo etcétera. Constituye la herramienta de álgebra lineal. Aquí, la [documentación](https://numpy.org/doc/stable/) y el [código fuente](https://github.com/numpy/numpy). 

Numpy suele venir instalado por defecto en el paquete de Python. Si no lo está, podemos instalarlo con el siguiente comando:

```bash
pip install numpy
```

## 2 - Recordatorio de álgebra

El álgebra es la rama de la matemática que estudia la combinación de elementos de estructuras abstractas acorde a ciertas reglas. Originalmente esos elementos podían ser interpretados como números o cantidades, por lo que el álgebra en cierto modo fue originalmente una generalización y extensión de la aritmética. Veamos algunos conceptos algebraicos.

### 2.1 - Concepto de tensor

La palabra ['tensor'](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) se utiliza a menudo como abreviatura de campo tensorial, que es un valor tensorial definido en cada punto en una variedad. El primero en utilizar esta palabra fue William Rowan Hamilton en 1846, empleándola para lo que actualmente se conoce como módulo y fue Woldemar Voigt en 1899 quien la empleó en su acepción actual. La palabra tensor proviene del latín tensus, participio pasado de tendere 'estirar, extender'. El nombre se extendió porque la teoría de la elasticidad fue una de las primeras aplicaciones físicas donde se usaron tensores. Gregorio Ricci-Curbastro en 1890 desarrolló la notación actual con el nombre de geometría diferencial absoluta, y se popularizó con la publicación de Cálculo Diferencial Absoluto de Tullio Levi-Civita en 1900. Con la introducción de la teoría de la relatividad general por parte de Albert Einstein alrededor de 1915 se encontró su aplicación más pragmática. La Relatividad General es netamente tensorial. Einstein había aprendido del mismo Levi-Civita el uso de tensores con gran dificultad.

Podemos pensar en un tensor como la generalización del ente algebraico. Con un ejemplo se verá más claro.

Un **número**, cualquier número, $2$, $3.6$, $\pi$, $\phi$, $\sqrt{2}$, es un **tensor de rango $0$**.

Un **vector**, cualquier vector, sea como sea su longitud, $(1, 2, 3)$, $(0, 5, 2, 1, 5)$, $(9,2)$, es un **tensor de rango $1$**.

Una **matriz**, cualquier matriz, sean cuales sean sus dimensiones, es un **tensor de rango $2$**.

Un **cubo de Rubik** por ejemplo es un **tensor de rango $3$**.

Pensar en dimensiones superiores es complicado por no decir imposible, pero se pueden interpretar a través del contenido. Una **bolsa llena de cubos de Rubik** es un **tensor de rango $4$**.

Una **caja llena de bolsas que están llenas de cubos de Rubik es un tensor de rango $5$**.

Y así sucesivamente.

### 2.2 - Operaciones con vectores

#### 2.2.1 - Espacio vectorial

La definición matemática de [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) implica los conceptos de conjunto, ley de composición(operación) interna y ley de composición externa, definida sobre un segundo conjunto. Resumiendo, un espacio vectorial es una estructura creada sobre un conjunto no vacío con ambas leyes de composición. A los elementos de un espacio vectorial se les llama vectores.

Veamos un ejemplo:

Un espacio vectorial es el espacio tridimensional ${\Bbb R}^{3}$. Los elementos de ${\Bbb R}^{3}$ son vectores, por lo que la ley de composición interna es la suma de vectores. Para la ley de composición externa se necesita otro conjunto, que en esta caso son los números reales ${\Bbb R}$, y queda definida como el producto por escalares, multiplicar un vector por un número.

#### 2.2.2 - Base vectorial

Una [base](https://es.wikipedia.org/wiki/Base_(%C3%A1lgebra)) es un conjunto de vectores {$v_{1}, v_{2}, v_{3}, ... ,v_{n}$} que cumplen las siguientes propiedades:

+ Todos los elementos de la base pertenecen al mismo espacio vectorial.
+ Los elementos de la base forman un sistema linealmente independiente (ninguno es combinación lineal de los demás).
+ Cualquier elemento del espacio vectorial se puede escribir como combinación lineal de los elementos de la base (es lo que se llama sistema generador del espacio vectorial).

Ejemplo:

En ${\Bbb R}^{3}$, la base principal (llamada canónica) es {$(1,0,0), (0,1,0), (0,0,1)$}. Todos esos vectores pertenecen a ${\Bbb R}^{3}$, son linealmente independientes(ninguno puede ser una suma de los otros) y cualquier otro vector en ${\Bbb R}^{3}$ se puede representar como una suma de esos tres, una combinación lineal. No es única, otra base de ${\Bbb R}^{3}$ podría ser {$(1,1,1), (1,1,0), (1,0,0)$}


#### 2.2.3 - Suma de vectores

Los vectores se suman por componentes, lo que implica que ambos tienen la misma longitud. Por ejemplo en ${\Bbb R}^{3}$:

$$\vec{A}=A_{x}\vec{i}+A_{y}\vec{j}+A_{z}\vec{k}$$

$$\vec{B}=B_{x}\vec{i}+B_{y}\vec{j}+B_{z}\vec{k}$$

$$\vec{A}+\vec{B}=(B_{x}+A_{x})\vec{i}+(B_{y}+A_{y})\vec{j}+(B_{z}+A_{z})\vec{k}$$

$$$$

$$\vec{A}=(1,8,9)$$

$$\vec{B}=(4,3,0)$$

$$\vec{A}+\vec{B}=(5,11,9)$$


#### 2.2.4 - Producto escalar

Hay que diferenciar entre producto por escalares, un número por un vector resultando un vector, y el productor escalar donde se multiplican dos vectores resultando un número, un escalar.

+ Producto por escalares:

Se realiza elemento a elemento la multiplicación por el número:

$$\vec{A}=(1,8,9)$$

$$2*\vec{A}=(2,16,18)$$

+ Productos escalar:

Se realiza multiplicando elemento un vector fila por un vector columna y sumando los resultados. Hay que tener en cuenta, igual que en la suma, que ambos vectores tienen el mismo número de elementos. También se le llama producto punto (dot product) o producto interno (inner product).

$$\vec{A}\cdot\vec{B}=(1, 8, 9)\cdot\begin{pmatrix}4\\3\\0\end{pmatrix} = 1·4+8·3+9·0 = 4+24+0 = 28$$


#### 2.2.5 - Producto vectorial

En este caso, se multiplican dos vectores resultando otro vector. La manera más fácil de hacerlo es a través de un determinante:


$$\vec{A}\times \vec{B} = \begin{vmatrix}
\hat{\imath}&\hat{\jmath}&\hat{k}\\
1 & 8 & 9 \\
4 & 3 & 0
\end{vmatrix} = \begin{vmatrix}
8 & 9 \\
3 & 0
\end{vmatrix}·\hat{\imath} - 
\begin{vmatrix}
1 & 9 \\
4 & 0
\end{vmatrix}·\hat{\jmath} +
\begin{vmatrix}
1 & 8 \\
4 & 3
\end{vmatrix}·\hat{k} = (8·0-9·3)·\hat{\imath}-(1·0-9·4)·\hat{\jmath}+(1·3-8·4)·\hat{k}$$

$$\vec{A}\times \vec{B} = (-27, 36, -29)$$

### 2.3 - Operaciones con matrices

#### 2.3.1 - Suma de matrices

Las matrices tienen definidas sus dimensiones sugún el número de filas($m$) y de columnas($n$), y se representan como $A_{mxn}$. Para sumar matrices las dimensiones tienen que ser las mismas, igual que ocurría con los vectores, y se realiza elemento a elemento (element wise):


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}+\begin{pmatrix}
0 & 0 & 3 \\
2 & 2 & 7 
\end{pmatrix}=\begin{pmatrix}
5 & 7 & 4 \\
6 & 2 & 9 
\end{pmatrix}$$

#### 2.3.2 - Producto matricial

Para multiplicar matrices tenemos que tener en cuenta las dimensiones, porque el producto matricial no es conmutativo e incluso a veces no se puede realizar. El número de columnas de la primera matriz tiene que ser igual que el número de filas de la segunda y el resultado tendrá el número de filas de la primera y el número de columnas de la segunda. Es decir:

$$A_{rxn}\cdot B_{nxq} = C_{rxq}$$


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}\cdot\begin{pmatrix}
0 & 0 \\
2 & 3 \\
2 & 7 
\end{pmatrix}=\begin{pmatrix}
5·0+7·2+1·2 & 5·0+7·3+1·7 \\
4·0+0·2+2·2 & 4·0+0·3+2·7
\end{pmatrix}=\begin{pmatrix}
18 & 28 \\
4 & 14
\end{pmatrix}$$

#### 2.3.3 - Matriz Identidad

Elemento neutro de la multiplicación, solo $1_s$ en la diagonal:

$$I = \begin{pmatrix}
1&0&\cdots&0&0\\
0&1&\cdots&0&0\\
\vdots&\vdots&\ddots&\vdots&\vdots\\
0&\cdots&\cdots&\cdots&0\\
0&0&\cdots&1&0\\
0&0&\cdots&0&1\\
\end{pmatrix}$$

#### 2.3.4 - Matriz traspuesta  (hermítica)

La traspuesta $A^{T}$ de una matriz $A$ puede ser obtenida reflejando los elementos a lo largo de su diagonal.

$$A=\begin{pmatrix}
5 & 7 & 9 \\
4 & 0 & 7 \\
1 & 2 & 2
\end{pmatrix}$$

$$A^{T}=\begin{pmatrix}
5 & 4 & 1 \\
7 & 0 & 2 \\
9 & 7 & 2
\end{pmatrix}$$


Se le dice hermítica si los elementos son números complejos, es la traspuesta conjugada (el conjugado de $x+iy$ es $x-iy$).


#### 2.3.5 - Matriz Inversa

¿Como se dividen las matrices? Se multiplica por la inversa, pues no existe la operación división para las matrices. El cálculo de la matriz inversa se puede hacer por el método de Gauss o de manera más sencilla:

$$A= \begin{pmatrix}
       a_{11} & a_{12} \\ 
       a_{21} & a_{22}
    \end{pmatrix}$$
    
    
$$A^{-1}=\begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}^{-1}
=\frac{1}{\lvert A\rvert}
\begin{pmatrix}
a_{22} & -a_{12} \\ 
-a_{21} &  a_{11}
\end{pmatrix}$$

#### 2.3.6 - Determinante

El determinante de una matriz es un número. Conocer el determinante de una matriz tiene varios usos. Uno de ellos es resolver un sistema de ecuaciones lineal. También nos sirve para calcular la inversa de una matriz, el rango de una matriz o áreas de un plano, entre otras operaciones. Para que una matriz tenga determinante, es necesario que sea cuadrada, es decir, que tenga el mismo número de filas y columnas. De lo contrario, la matriz no tendrá un determinante.



$$A=\begin{pmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{pmatrix}$$
  

$$$$


$$det(A)=\begin{vmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 0 & 0 \\ 
    -2 & 1 & 0 \\ 
    -2 & 0 & 1
  \end{vmatrix}\cdot
  \begin{vmatrix}
    1 & 4 & 1 \\ 
    2 & 6 & 3 \\ 
    2 & 10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 4 & 1 \\ 
    0 & -2 & 1 \\ 
    0 & 2 & 1
  \end{vmatrix}
  =
  \begin{vmatrix}
    -2 & 1 \\ 
    2 & 1
  \end{vmatrix}
  =-4$$

## 3 - Operaciones con NumPy

In [1]:
import numpy as np

### 3.1 - Creación de arrays

In [2]:
# nº aleatorio

np.random.random(1)

array([0.06270523])

In [4]:
# vector

vector = np.random.random(3)

vector

array([0.95838592, 0.44765657, 0.25356653])

In [5]:
type(vector)

numpy.ndarray

In [6]:
# matriz

matriz = np.random.random((10, 4))

matriz

array([[0.48109826, 0.30940098, 0.58033676, 0.78477373],
       [0.55148065, 0.30130801, 0.49925205, 0.66931179],
       [0.37922522, 0.9109447 , 0.25494026, 0.08178075],
       [0.66065679, 0.87877676, 0.32754796, 0.63123097],
       [0.50335743, 0.12839078, 0.37630036, 0.43507551],
       [0.3380827 , 0.65198261, 0.12961856, 0.72812614],
       [0.79422305, 0.47836228, 0.00211945, 0.10652424],
       [0.30571149, 0.46025486, 0.81656482, 0.29582646],
       [0.2331184 , 0.16202035, 0.81413503, 0.61233515],
       [0.18857015, 0.70710913, 0.47713318, 0.1020249 ]])

In [7]:
# cubo 

cubo = np.random.random((3, 2, 3))

cubo

array([[[0.37123832, 0.20975298, 0.20204886],
        [0.29699024, 0.79403698, 0.69791082]],

       [[0.15857794, 0.80325027, 0.99484584],
        [0.41069678, 0.79693985, 0.42724261]],

       [[0.11190008, 0.81718533, 0.215276  ],
        [0.21943194, 0.26295884, 0.25391224]]])

In [8]:
# tensor 

tensor = np.random.random((2, 3, 4, 5))

tensor

array([[[[0.3722862 , 0.73776361, 0.88238095, 0.01346938, 0.18837309],
         [0.80036172, 0.25105888, 0.25651851, 0.42370584, 0.95211806],
         [0.40838395, 0.32344128, 0.22329266, 0.99264905, 0.04622368],
         [0.03999243, 0.7508564 , 0.2835343 , 0.10588172, 0.5056635 ]],

        [[0.67518612, 0.606057  , 0.88742251, 0.40380171, 0.89919059],
         [0.37407904, 0.9627731 , 0.04441872, 0.64184857, 0.12460229],
         [0.14293215, 0.67028651, 0.98459871, 0.45689841, 0.4721    ],
         [0.73691211, 0.90637285, 0.65207036, 0.65070753, 0.47968598]],

        [[0.59311963, 0.73737137, 0.89885474, 0.15970677, 0.61774943],
         [0.69427925, 0.75726296, 0.64357666, 0.0509524 , 0.18477414],
         [0.50501625, 0.49097808, 0.65114908, 0.81581144, 0.55819875],
         [0.12955986, 0.8769677 , 0.61675131, 0.63502534, 0.01281995]]],


       [[[0.97377342, 0.31995586, 0.47368454, 0.60935696, 0.6612998 ],
         [0.12591455, 0.82641418, 0.12477577, 0.89962281, 0.97827139]

In [9]:
type(tensor)

numpy.ndarray

### 3.2 - Dimensiones y acceso a elementos

Vamos a ver esos métodos para ver las dimensiones y número de elementos que hay enn un array. Además, en los array de NumPy podemos acceder a los elementos en su interior de la misma manera que lo haríamos con una lista, con los índices y también usando slicing.

In [10]:
vector.shape

(3,)

In [11]:
matriz.shape

(10, 4)

In [12]:
cubo.shape

(3, 2, 3)

In [13]:
matriz

array([[0.48109826, 0.30940098, 0.58033676, 0.78477373],
       [0.55148065, 0.30130801, 0.49925205, 0.66931179],
       [0.37922522, 0.9109447 , 0.25494026, 0.08178075],
       [0.66065679, 0.87877676, 0.32754796, 0.63123097],
       [0.50335743, 0.12839078, 0.37630036, 0.43507551],
       [0.3380827 , 0.65198261, 0.12961856, 0.72812614],
       [0.79422305, 0.47836228, 0.00211945, 0.10652424],
       [0.30571149, 0.46025486, 0.81656482, 0.29582646],
       [0.2331184 , 0.16202035, 0.81413503, 0.61233515],
       [0.18857015, 0.70710913, 0.47713318, 0.1020249 ]])

In [14]:
matriz[0]  # 1ª fila

array([0.48109826, 0.30940098, 0.58033676, 0.78477373])

In [15]:
matriz[0][0]

0.48109826335811745

In [16]:
matriz[0, 0]

0.48109826335811745

In [17]:
# primera columna

matriz[:, 0]

array([0.48109826, 0.55148065, 0.37922522, 0.66065679, 0.50335743,
       0.3380827 , 0.79422305, 0.30571149, 0.2331184 , 0.18857015])

In [18]:
# slicing, filas 1,3,5,7

matriz[0:8:2]

array([[0.48109826, 0.30940098, 0.58033676, 0.78477373],
       [0.37922522, 0.9109447 , 0.25494026, 0.08178075],
       [0.50335743, 0.12839078, 0.37630036, 0.43507551],
       [0.79422305, 0.47836228, 0.00211945, 0.10652424]])

In [19]:
matriz[0:8:2, 1:4:2]

array([[0.30940098, 0.78477373],
       [0.9109447 , 0.08178075],
       [0.12839078, 0.43507551],
       [0.47836228, 0.10652424]])

### 3.3 - Suma de vectores

Recordemos que los vectores se suman componente a componente en contraposición a lo que hacen las listas, que se concatenan.

In [20]:
vector

array([0.95838592, 0.44765657, 0.25356653])

In [21]:
vector + vector

array([1.91677183, 0.89531315, 0.50713306])

In [22]:
[1, 2, 3] + [1, 2, 3]

[1, 2, 3, 1, 2, 3]

### 3.4 - Producto por escalares 

Exactamente igual que en el ejemplo anterior, al multiplicar un vector por un número se multiplica elemento a elemento, las listas se repiten.

In [23]:
3 * vector

array([2.87515775, 1.34296972, 0.76069958])

In [24]:
3 * [1, 2, 3]

[1, 2, 3, 1, 2, 3, 1, 2, 3]

### 3.5 - Producto escalar de vectores

Vamos a multiplicar dos vectores con el mismo número de elementos y el resultado será un número. Este producto se realiza con el método `np.dot` que proporciona NumPy.

In [25]:
np.dot(vector, vector)

1.1831959571907107

### 3.6 - Producto vectorial

Para realizar el producto vectorial, NumPy tiene un método `np.cross`, el cual recibe dos vectores y devuelve un vector resultado del producto.

In [26]:
np.cross(vector, vector+1)

array([ 0.19409004, -0.70481939,  0.51072934])

### 3.7 - Suma de matrices

In [27]:
matriz

array([[0.48109826, 0.30940098, 0.58033676, 0.78477373],
       [0.55148065, 0.30130801, 0.49925205, 0.66931179],
       [0.37922522, 0.9109447 , 0.25494026, 0.08178075],
       [0.66065679, 0.87877676, 0.32754796, 0.63123097],
       [0.50335743, 0.12839078, 0.37630036, 0.43507551],
       [0.3380827 , 0.65198261, 0.12961856, 0.72812614],
       [0.79422305, 0.47836228, 0.00211945, 0.10652424],
       [0.30571149, 0.46025486, 0.81656482, 0.29582646],
       [0.2331184 , 0.16202035, 0.81413503, 0.61233515],
       [0.18857015, 0.70710913, 0.47713318, 0.1020249 ]])

In [28]:
matriz + matriz

array([[0.96219653, 0.61880195, 1.16067351, 1.56954746],
       [1.1029613 , 0.60261603, 0.99850411, 1.33862358],
       [0.75845044, 1.82188939, 0.50988053, 0.1635615 ],
       [1.32131358, 1.75755353, 0.65509593, 1.26246193],
       [1.00671487, 0.25678157, 0.75260071, 0.87015103],
       [0.67616539, 1.30396521, 0.25923711, 1.45625227],
       [1.58844611, 0.95672456, 0.00423891, 0.21304848],
       [0.61142299, 0.92050972, 1.63312965, 0.59165293],
       [0.4662368 , 0.32404071, 1.62827006, 1.22467029],
       [0.37714031, 1.41421825, 0.95426635, 0.20404981]])

### 3.8 - Producto escalar de matrices

In [29]:
5 * matriz

array([[2.40549132, 1.54700489, 2.90168378, 3.92386865],
       [2.75740325, 1.50654006, 2.49626027, 3.34655894],
       [1.89612609, 4.55472348, 1.27470131, 0.40890376],
       [3.30328396, 4.39388382, 1.63773982, 3.15615484],
       [2.51678716, 0.64195391, 1.88150178, 2.17537757],
       [1.69041348, 3.25991303, 0.64809278, 3.64063068],
       [3.97111527, 2.3918114 , 0.01059727, 0.53262119],
       [1.52855747, 2.30127431, 4.08282412, 1.47913231],
       [1.165592  , 0.81010177, 4.07067514, 3.06167574],
       [0.94285077, 3.53554563, 2.38566588, 0.51012452]])

### 3.9 - Producto matricial

Para multiplicar matrices, las dimensiones tienen que ser correctas, es decir, el número de columnas de la primera matriz tiene que ser igual al número de filas de la segunda. El resultado tendrá el número de filas de la primera matriz y el número de columnas de la segunda. Esta es la razón por la que el producto de matrices no es conmutativo. Esta operación se realiza con el método `np.matmul`.

In [30]:
matriz_1 = np.random.random((10, 4))

matriz_2 = np.random.random((4, 10))

In [31]:
np.matmul(matriz_1, matriz_2)

array([[0.82476305, 0.47670128, 0.48805732, 0.54593268, 0.21724204,
        0.73738481, 0.54241908, 0.49769168, 0.73805946, 0.32759859],
       [1.42466581, 0.93199204, 1.42591681, 1.46914555, 0.53170545,
        1.63958829, 1.57774501, 0.81902918, 1.29926191, 0.78542863],
       [0.8599162 , 0.75622384, 1.15979544, 1.20364228, 0.46497859,
        1.26860115, 1.34493075, 0.59909339, 1.06873703, 0.57037244],
       [1.76067857, 0.90775126, 1.57453059, 2.01814862, 0.61497196,
        1.8536528 , 1.72537636, 1.33683755, 1.7385854 , 0.83924459],
       [0.80959584, 0.64284059, 0.97721439, 1.1849774 , 0.4255165 ,
        1.12308277, 1.14843992, 0.72292113, 1.12137594, 0.46632589],
       [0.73723056, 0.83768547, 1.06399531, 1.0880488 , 0.48305852,
        1.23537647, 1.29934065, 0.59377688, 1.18366159, 0.50718174],
       [1.30148924, 1.04844985, 1.15868879, 1.41670313, 0.58094833,
        1.57963236, 1.40930461, 1.10759148, 1.78258624, 0.61192253],
       [0.66471043, 0.67635275, 0.3881058

In [32]:
np.matmul(matriz_2, matriz_1)

array([[2.23537954, 2.74279377, 2.56813594, 2.44992216],
       [2.48651987, 2.77001183, 2.58628789, 2.45745248],
       [2.36954279, 2.20480296, 2.17230367, 2.35276864],
       [2.23031034, 2.84431842, 2.07878961, 3.01884815]])

In [33]:
np.matmul(matriz_1, matriz_1)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 10 is different from 4)

### 3.10 - Matriz identidad

Vimos que esta matriz es el elemento neutro del producto, una matriz que se multiplica por la matriz identidad devuelve la misma matriz. La matriz identidad es un matriz con todo ceros salvo en la diagonal, que tiene unos. Se construye con el método `np.eye`.

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 3.11 - Matriz traspuesta

La matriz traspuesta es una matriz que cambia filas por columnas. Una vez creada la matriz se puede calcular su traspuesta usando el atributo `.T` o el método `.transpose()`.

In [40]:
matriz_2.shape

(4, 10)

In [42]:
matriz_2.T.shape

(10, 4)

In [43]:
matriz.transpose()

array([[0.48109826, 0.55148065, 0.37922522, 0.66065679, 0.50335743,
        0.3380827 , 0.79422305, 0.30571149, 0.2331184 , 0.18857015],
       [0.30940098, 0.30130801, 0.9109447 , 0.87877676, 0.12839078,
        0.65198261, 0.47836228, 0.46025486, 0.16202035, 0.70710913],
       [0.58033676, 0.49925205, 0.25494026, 0.32754796, 0.37630036,
        0.12961856, 0.00211945, 0.81656482, 0.81413503, 0.47713318],
       [0.78477373, 0.66931179, 0.08178075, 0.63123097, 0.43507551,
        0.72812614, 0.10652424, 0.29582646, 0.61233515, 0.1020249 ]])

### 3.12 - Matriz inversa

Decíamos que para dividir matrices teníamos que calcular la inversa. Esto quiere decir que si multiplicamos una matriz por su inversa saldrá la matriz identidad. NumPy tiene el módulo `linalg`, el cual tiene el método `inv` para realizar esta operación.

In [44]:
from numpy.linalg import inv

In [45]:
matriz = np.random.random((3, 3))

matriz

array([[0.35814511, 0.08041552, 0.0632703 ],
       [0.07838014, 0.40306924, 0.83833243],
       [0.73976694, 0.86538467, 0.70650104]])

In [46]:
inv(matriz)

array([[ 3.47031761,  0.01622512, -0.33003503],
       [-4.44739759, -1.62388638,  2.32518384],
       [ 1.81384509,  1.9720899 , -1.08708891]])

In [47]:
np.matmul(matriz, inv(matriz))

array([[ 1.00000000e+00, -3.29519269e-17,  6.08678011e-17],
       [-1.01894395e-16,  1.00000000e+00, -8.70788010e-18],
       [-2.84411546e-16, -4.82287933e-17,  1.00000000e+00]])

### 3.13 - Determinante

El módulo `linalg`, también tiene el método `det` para calcular el determinante de una matriz. Vimos que no podía ser cero para calcular la matriz inversa.

In [48]:
from numpy.linalg import det

In [49]:
det(matriz)

-0.12699448455049542

### 3.14 - Otra operaciones

NumPy es una librería realmente grande. Con ella se pueden hacer multitud de operaciones y transformaciones, como el cálculo del mínimo, el máximo, la media o la desviación estandar. Vamos a ver algunas de esas operaciones que nos proporciona NumPy.

In [51]:
matriz = np.random.random((10, 4))

matriz

array([[0.39451183, 0.69728752, 0.84212474, 0.80363268],
       [0.91212088, 0.92175549, 0.11526855, 0.15645495],
       [0.14468113, 0.65383038, 0.06836297, 0.07055831],
       [0.76558053, 0.74069201, 0.40851154, 0.17700496],
       [0.00445504, 0.63127721, 0.81897758, 0.15713056],
       [0.51537956, 0.58640824, 0.80467651, 0.650851  ],
       [0.37506257, 0.9499508 , 0.06164917, 0.57580375],
       [0.77441744, 0.62776658, 0.30093834, 0.5973944 ],
       [0.09080517, 0.87641358, 0.53332645, 0.46107891],
       [0.01850809, 0.45941211, 0.05300036, 0.28458822]])

In [52]:
matriz.min()

0.004455041495789791

In [53]:
matriz.max()

0.9499507952607109

In [54]:
matriz.sum()

19.08165009289494

Estos métodos tienen un argumento llamada `axis`, el cual nos permite realizar el cálculo según los ejes del array, es decir, según sus dimensiones.

In [55]:
# sumar por columnas

matriz.sum(axis=0)

array([3.99552224, 7.14479392, 4.0068362 , 3.93449774])

In [56]:
 # sumar por filas

matriz.sum(axis=1)

array([2.73755676, 2.10559986, 0.93743278, 2.09178904, 1.61184039,
       2.55731531, 1.96246628, 2.30051676, 1.96162412, 0.81550878])

In [57]:
matriz.mean()

0.4770412523223735

In [58]:
np.median(matriz)

0.5243530085504085

In [59]:
matriz.std()

0.2986351815802402

In [60]:
np.prod(matriz)

8.393432793441453e-21

In [61]:
np.multiply(matriz[0], matriz[1])

array([0.35984248, 0.6427286 , 0.0970705 , 0.12573231])

In [62]:
matriz.cumsum()

array([ 0.39451183,  1.09179935,  1.93392409,  2.73755676,  3.64967764,
        4.57143313,  4.68670168,  4.84315663,  4.98783775,  5.64166813,
        5.7100311 ,  5.78058941,  6.54616993,  7.28686194,  7.69537348,
        7.87237845,  7.87683349,  8.5081107 ,  9.32708828,  9.48421883,
        9.9995984 , 10.58600664, 11.39068315, 12.04153415, 12.41659672,
       13.36654751, 13.42819668, 14.00400043, 14.77841787, 15.40618445,
       15.70712279, 16.30451719, 16.39532236, 17.27173594, 17.8050624 ,
       18.26614131, 18.2846494 , 18.74406151, 18.79706187, 19.08165009])

In [63]:
matriz.cumprod()

array([3.94511832e-01, 2.75088177e-01, 2.31658558e-01, 1.86168387e-01,
       1.69808072e-01, 1.56521523e-01, 1.80420086e-02, 2.82276155e-03,
       4.08400324e-04, 2.67024538e-04, 1.82545906e-05, 1.28801298e-06,
       9.86077655e-07, 7.30379838e-07, 2.98368594e-07, 5.28127220e-08,
       2.35282868e-10, 1.48528713e-10, 1.21641686e-10, 1.91136258e-11,
       9.85077209e-12, 5.77657395e-12, 4.64827335e-12, 3.02533337e-12,
       1.13468930e-12, 1.07789900e-12, 6.64515742e-14, 3.82630657e-14,
       2.96315854e-14, 1.86017191e-14, 5.59797043e-15, 3.34419619e-15,
       3.03670320e-16, 2.66140792e-16, 1.41939925e-16, 6.54455061e-17,
       1.21127133e-18, 5.56472720e-19, 2.94932543e-20, 8.39343279e-21])

In [64]:
np.inf

inf

In [65]:
np.pi

3.141592653589793

In [66]:
np.nan

nan

In [67]:
type(np.nan)

float

In [68]:
type(np.inf)

float

In [69]:
type(np.pi)

float

In [71]:
np.exp(5)

148.4131591025766

In [72]:
np.cos(3)

-0.9899924966004454

In [73]:
np.sin(7)

0.6569865987187891

In [74]:
np.log(6)

1.791759469228055

In [78]:
matriz.reshape((5, 8)).shape

(5, 8)

In [81]:
matriz.flatten().shape

(40,)

In [82]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [84]:
# condicional

np.where(matriz > 0.5, 1, 0)   # if > 0.5 1 else 0

array([[0, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [85]:
np.where(matriz > 0.5, 1, np.where(matriz<0.5, 2, 0))

array([[2, 1, 1, 1],
       [1, 1, 2, 2],
       [2, 1, 2, 2],
       [1, 1, 2, 2],
       [2, 1, 1, 2],
       [1, 1, 1, 1],
       [2, 1, 2, 1],
       [1, 1, 2, 1],
       [2, 1, 1, 2],
       [2, 2, 2, 2]])

In [87]:
np.array([1,2,3]) * 4

array([ 4,  8, 12])